# Generated by Django 2.1.1 on 2018-09-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_photo',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
