# Generated by Django 2.1.1 on 2018-09-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50)),
                ('work_type', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.IntegerField()),
                ('quiz_question', models.CharField(max_length=500)),
                ('quiz_option', models.CharField(max_length=1000, null=True)),
                ('CourseWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseWork')),
            ],
        ),
    ]
