# Generated by Django 2.1.1 on 2018-09-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_coursework_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_option',
        ),
        migrations.AddField(
            model_name='coursework',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursework',
            name='lecture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_options',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='right_option',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='work_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lecture'), (2, 'Quiz')], null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One Option'), (2, 'Multiple Select')], null=True),
        ),
    ]
