# Generated by Django 2.1.1 on 2018-09-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20180921_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
