# Generated by Django 2.1.1 on 2018-09-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20180921_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='next_course_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.CourseWork'),
        ),
    ]
