# Generated by Django 2.1.1 on 2018-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_coursework_next_course_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
