# Generated by Django 2.1.1 on 2018-09-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180921_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='current_course_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.CourseWork'),
        ),
    ]
