# Generated by Django 2.1.1 on 2018-09-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180921_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquiz',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myquiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
