# Generated by Django 2.1.1 on 2018-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180921_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myquiz',
            old_name='marks',
            new_name='obtained_marks',
        ),
        migrations.AddField(
            model_name='myquiz',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
